export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './gamesController.service';
import { GamesControllerService } from './gamesController.service';
export * from './matchesController.service';
import { MatchesControllerService } from './matchesController.service';
export * from './newsController.service';
import { NewsControllerService } from './newsController.service';
export * from './profileController.service';
import { ProfileControllerService } from './profileController.service';
export * from './publishTest.service';
import { PublishTestService } from './publishTest.service';
export * from './teamsController.service';
import { TeamsControllerService } from './teamsController.service';
export const APIS = [BasicErrorControllerService, GamesControllerService, MatchesControllerService, NewsControllerService, ProfileControllerService, PublishTestService, TeamsControllerService];
