export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './gameEntity.service';
import { GameEntityService } from './gameEntity.service';
export * from './gamesController.service';
import { GamesControllerService } from './gamesController.service';
export * from './matchEntity.service';
import { MatchEntityService } from './matchEntity.service';
export * from './matchesController.service';
import { MatchesControllerService } from './matchesController.service';
export * from './newsController.service';
import { NewsControllerService } from './newsController.service';
export * from './newsEntity.service';
import { NewsEntityService } from './newsEntity.service';
export * from './profileController.service';
import { ProfileControllerService } from './profileController.service';
export * from './publishTest.service';
import { PublishTestService } from './publishTest.service';
export * from './teamEntity.service';
import { TeamEntityService } from './teamEntity.service';
export * from './teamMatchScoreEntity.service';
import { TeamMatchScoreEntityService } from './teamMatchScoreEntity.service';
export * from './teamMemberEntity.service';
import { TeamMemberEntityService } from './teamMemberEntity.service';
export const APIS = [BasicErrorControllerService, GameEntityService, GamesControllerService, MatchEntityService, MatchesControllerService, NewsControllerService, NewsEntityService, ProfileControllerService, PublishTestService, TeamEntityService, TeamMatchScoreEntityService, TeamMemberEntityService];
