/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedCollectionOfMatch } from './embeddedCollectionOfMatch';
import { Link } from './link';


/**
 * Resources of Match
 */
export interface CollectionModelOfMatch { 
    _embedded: EmbeddedCollectionOfMatch;
    /**
     * Link collection
     */
    _links: { [key: string]: Link; };
}

