/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameDto { 
    codeName?: string;
    description?: string;
    designer?: string;
    genre?: string;
    minAge?: number;
    name?: string;
    platform?: string;
    profitModel?: string;
    publisher?: string;
    releaseDate?: string;
}

