/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Game { 
    codeName?: Game.CodeNameEnum;
    description?: string;
    designer?: string;
    genre?: string;
    minAge?: number;
    name?: string;
    platform?: string;
    profitModel?: string;
    publisher?: string;
    releaseDate?: string;
}
export namespace Game {
    export type CodeNameEnum = 'CODMW' | 'DOTA2' | 'LOL' | 'VALORANT';
    export const CodeNameEnum = {
        Codmw: 'CODMW' as CodeNameEnum,
        Dota2: 'DOTA2' as CodeNameEnum,
        Lol: 'LOL' as CodeNameEnum,
        Valorant: 'VALORANT' as CodeNameEnum
    };
}


