/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMatchScoreDto } from './teamMatchScoreDto';


export interface MatchesDto { 
    inProgress?: boolean;
    matchTime?: string;
    teams?: Array<TeamMatchScoreDto>;
    title?: string;
}

