/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMatchScoreDto } from './teamMatchScoreDto';


export interface MatchDto {
    game?: string;
    id?: number;
    name?: string;
    scheduledAt?: string;
    status?: MatchDto.StatusEnum;
    teams?: Array<TeamMatchScoreDto>;
}
export namespace MatchDto {
    export type StatusEnum = 'CANCELED' | 'FINISHED' | 'NOT_STARTED' | 'POSTPONED' | 'RUNNING';
    export const StatusEnum = {
        Canceled: 'CANCELED' as StatusEnum,
        Finished: 'FINISHED' as StatusEnum,
        NotStarted: 'NOT_STARTED' as StatusEnum,
        Postponed: 'POSTPONED' as StatusEnum,
        Running: 'RUNNING' as StatusEnum
    };
}


