/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Game } from './game';


export interface News { 
    content?: string;
    date?: string;
    description?: string;
    game?: Game;
    id?: number;
    image?: string;
    publisher?: string;
    title?: string;
}

