/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMatchPrimaryKey } from './teamMatchPrimaryKey';
import { Team } from './team';


export interface TeamMatchScoreRes { 
    id?: TeamMatchPrimaryKey;
    _new?: boolean;
    score?: number;
    team?: Team;
}

