/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TeamMemberDto { 
    birthYear?: string;
    birthday?: string;
    firstName?: string;
    hometown?: string;
    imageUrl?: string;
    lastName?: string;
    name?: string;
    nationality?: string;
}

